name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip3 install coverage          
          pip3 install flask
          pip3 install flask-wtf
          pip3 install flask-sqlalchemy
          pip3 install email-validator
          pip3 install flask-bcrypt
          pip3 install speechRecognition
          pip3 install turbo-flask

      - name: Test webpages
        run: python3 tests/test_basic.py
      - name: Test webpages
        run: python3 tests/test_users.py
      - name: Check code coverage                        #new from here down
        run: |
          python3 -m coverage run -m unittest main.py
          python3 -m coverage run -m unittest test_basic.py
          python3 -m coverage run -m unittest test_users.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov